import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          {/* Meta tags */}
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
        <link rel="icon" href="/img/favicon.png" />

        {/* Styles */}
       
         <link rel="stylesheet" href="/css/plugins/bootstrap.min.css"/>
         <link rel="stylesheet" href="/css/plugins/font-awesome-pro.css"/>
         <link rel="stylesheet" href="/css/plugins/flaticon.css"/>
          <link
          href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
        
      </head>
      <body>
        {children}
          <Script src="js/popper.min.js" strategy="afterInteractive" />
        <Script src="js/bootstrap.min.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
